Repository agiledev-students-spring-2023/final-project-stoopit-project, pull requests merged in 2023-04, with the labels that each got.

#59 Unit test
  back-end/app.js
  back-end/mockData/stoopDatabase.js
  back-end/package.json
  back-end/tests/spec/app.test.js
  back-end/tests/spec/utils/distance.test.js
  back-end/utils/distance.js
  back-end/utils/random.js
Labels: task

#61 Integrate feed page with BE endpoint
  front-end/package-lock.json
  front-end/package.json
  front-end/src/components/Card/Card.css
  front-end/src/components/Card/Card.jsx
  front-end/src/routes/feed/FeedPage.jsx
Labels: task

#62 53 stoop add endpoint
  back-end/app.js
  back-end/package.json
  front-end/src/components/SubmitForm/SubmitForm.jsx
Labels: task

#66 Fix img uploading
  .gitignore
  back-end/app.js
  front-end/src/components/Card/Card.jsx
  front-end/src/components/SubmitForm/SubmitForm.jsx
Labels: bug

#69 Added get stoops by ID endpoint
  back-end/app.js
Labels: task

#72 Unit test
  back-end/app.js
  back-end/package.json
  back-end/tests/spec/app.test.js
  back-end/tests/spec/utils/random.test.js
  back-end/utils/random.js
  package-lock.json
  package.json
Labels: task

#73 Cleaned repo
  .husky/pre-commit
  .husky/pre-push
  back-end/package.json
  back-end/tests/spec/app.test.js
  back-end/tests/spec/utils/distance.test.js
  back-end/tests/spec/utils/random.test.js
  back-end/utils/distance.js
  back-end/utils/random.js
  front-end/package-lock.json
  front-end/package.json
  front-end/src/components/Card/Card.jsx
  front-end/src/components/Card/__tests__/Card.test.js
  front-end/src/containers/App/__tests__/App.test.js
  front-end/src/routes/feed/FeedPage.jsx
  package-lock.json
  package.json
Labels: chore

#90 Fix husky stuff again
  back-end/app.js
  back-end/package.json
  front-end/package.json
  front-end/src/components/SpinnerLoader/SpinnerLoader.css
  front-end/src/components/SpinnerLoader/SpinnerLoader.jsx
  front-end/src/routes/feed/FeedPage.jsx
  package.json
Labels: chore

#98 Refactored map.js and location.js
  front-end/src/components/Card/Card.jsx
  front-end/src/components/SubmitForm/SubmitForm.jsx
  front-end/src/components/TopNav/TopNav.jsx
  front-end/src/routes/feed/FeedPage.jsx
  front-end/src/utils/location.js
  front-end/src/utils/map.js
Labels: task

#99 Fixing images and wip base64 stuff
  .gitignore
  back-end/app.js
  back-end/models/stoop.js
  back-end/uploads/1681409857813mattress.jpg
  back-end/uploads/1681845173201bluesofa.jpg
  back-end/uploads/1681845362163mattress.jpg
  back-end/uploads/1681848461812mattress.jpg
  front-end/package-lock.json
  front-end/package.json
  front-end/src/components/Card/Card.jsx
  front-end/src/components/SubmitForm/SubmitForm.jsx
  front-end/src/routes/upload/UploadPage.jsx
  front-end/src/utils/image.js
  package.json
Labels: chore
